[workspace]
git_release_enable = false
dependencies_update = true

git_release_body = """
{{ changelog }}
{% if remote.contributors %}
### Contributors
{% for contributor in remote.contributors %}
* @{{ contributor.username }}
{% endfor %}
{% endif %}
"""

[[package]]
name = "scruitny"
changelog_update = true
changelog_path = "CHANGELOG.md"
