# This is free and unencumbered software released into the public domain.

[workspace]
git_release_enable = false
dependencies_update = false

git_release_body = """
{{ changelog }}
{% if remote.contributors %}
### Contributors
{% for contributor in remote.contributors %}
* @{{ contributor.username }}
{% endfor %}
{% endif %}
"""

[[package]]
name = "scruitny"
git_tag_enable = true
git_release_enable = true
release = true
changelog_path = "CHANGELOG.md"
